- name: Setup Arch WSL
  hosts: localhost
  vars:
    username: hiterm
  tasks:
  - name: check if cargo is installed
    ansible.builtin.command: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Install cargo
    when: cargo_exists is failed
    ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y --no-modify-path
