- name: Setup Arch WSL
  hosts: localhost
  vars:
    username: hiterm
  tasks:
  - name: Install packages
    community.general.pacman:
      name:
        - chezmoi
    become: yes
  - name: chezmoi init
    ansible.builtin.command:
      argv:
        - chezmoi
        - init
        - hiterm/dotfiles-chezmoi
  - name: chezmoi apply
    ansible.builtin.command:
      argv:
        - chezmoi
        - apply
  - name: Install packages
    community.general.pacman:
      name:
        - zsh
        - git
        - fzf
        - openssh
        - ripgrep
    become: yes
  - name: chsh
    ansible.builtin.command:
      argv:
        - chsh
        - -s
        - /usr/bin/zsh
        - "{{ username }}"
    become: yes
