- name: Setup Arch WSL
  hosts: localhost
  vars:
    username: hiterm
  tasks:
  - name: Install packages
    community.general.pacman:
      name:
        - chezmoi
    become: yes
  - name: chezmoi init
    ansible.builtin.command:
      argv:
        - chezmoi
        - init
        - hiterm/dotfiles-chezmoi
  - name: chezmoi apply
    ansible.builtin.command:
      argv:
        - chezmoi
        - apply
  - name: Install packages
    community.general.pacman:
      name:
        - wget
        - zsh
        - git
        - fzf
        - openssh
        - ripgrep
        - neovim
        - bat
        - zoxide
        - sheldon
        - man-db
        - git-delta
    become: yes

  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel
  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'
  - name: Install paru using makepkg if it isn't installed already
    kewlfft.aur.aur:
      name: paru-bin
      use: makepkg
      state: present
    become: yes
    become_user: aur_builder
  - name: Install AUR packages
    kewlfft.aur.aur:
      use: paru
      name:
        - ghq-bin

  - name: chsh
    ansible.builtin.command:
      argv:
        - chsh
        - -s
        - /usr/bin/zsh
        - "{{ username }}"
    become: yes
